### ISSUE TITLE
Custom action/notification

### ISSUE THREAD

**Issue by Letrab** [naimo84/node-red-contrib-sonos-http-api#4]
Hi,

Thank you for your work on this lib.

Would it be possible to add a Custom field (in the notification) to call your own action?
I've added my own action, based on `clipall`, but which returns immediate, to speed it up, as discussed in: https://github.com/jishi/node-sonos-http-api/issues/502

Would be nice to be able to call it in your plugin.

Thanks!

**Comment by naimo84** [comment]
Hi,

sorry for the late response, I'll have a look at it and will report back. 

Greets,
Benjamin

**Comment by Letrab** [comment]
Thanks for your response.

But my need for this has dropped in the meanwhile, as `node-sonos-http-api` does not support what I was trying to achieve.

But might be interesting for other users in the future.
Thanks!
